CREATE DATABASE `HOSPITALDB`;
USE `HOSPITALDB`;
CREATE TABLE `HOSPITAL`(
    `PH` INT,
    `NAME` VARCHAR(20),
    `AGE` INT,
    `GENDER` VARCHAR(7),
    `BP1` INT,
    `BP2` INT,
    `PULSE` INT,
    `ALLERGIES` VARCHAR(20),
    `HEIGHT` INT,
    `WEIGHT` INT,
    `PATIENT_DETAILS` VARCHAR(50),
    PRIMARY KEY(`PH`, `NAME`)
);
CREATE TABLE `STORAGE`(
    `PH` INT,
    `NAME` VARCHAR(20),
    `AGE` INT,
    `GENDER` VARCHAR(7),
    `BP1` INT,
    `BP2` INT,
    `PULSE` INT,
    `ALLERGIES` VARCHAR(20),
    `HEIGHT` INT,
    `WEIGHT` INT,
    `PATIENT_DETAILS` VARCHAR(50),
    PRIMARY KEY(`PH`, `NAME`)
);
